### ISSUE TITLE
[Question] Does go-raml include a parser for Go?

### ISSUE THREAD

**Issue by sichvoge** [Jumpscale/go-raml#101]
My question is very simple :) Looking at this fantastic project, and thanks for contributing, I wonder if that project includes a Go parser or something else?

**Comment by iwanbk** [comment]
yes, the parser is in `raml` directory. It was based on https://github.com/go-raml/raml.
Please use raml1.0-rc2 branch for the latest code.

**Comment by sichvoge** [comment]
nice thank you!
