### ISSUE TITLE
need better documentation

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#103]
## how to see generated docs in python server

![image](https://cloud.githubusercontent.com/assets/6021844/15790473/80ad59b6-29e2-11e6-9e2d-f4ff462e5d55.png)

no idea how to get there

**Comment by iwanbk** [comment]
```
how to see generated docs in python server
```

https://github.com/Jumpscale/go-raml#simple-home-page-and-api-docs

```
more detailed info how to use the examples
```
Have added few info  in INSTRUCTIONS.md of tutorial directory, which then give link to https://github.com/Jumpscale/go-raml#using-generated-code

```
info how to best edit & view a raml file
```
added link to API workbench https://github.com/Jumpscale/go-raml#viewing-and-editing-raml-file, vim is enough for simple case

```
explain how to do authentication with oauth2 & itsyou.online
```
our generated client lib doesn't have special feature to obtain oauth access_code & token, it only provide facility to send Authorization header on each request.

Just added docs about it in https://github.com/Jumpscale/go-raml/pull/127
