### ISSUE TITLE
why is there a large zip file?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#104]
![image](https://cloud.githubusercontent.com/assets/6021844/15790693/c6a3e72c-29e3-11e6-9523-c39efae20b28.png)

**Comment by iwanbk** [comment]
@despiegk it was a mistake, fixed in 0b0243953ccc224ca742ee659832b52b0011eb92.

Please use raml1.0-rc2 branch to check it.

**Comment by despiegk** [comment]
Please merge in master

**Comment by iwanbk** [comment]
merged in PR #106
