### ISSUE TITLE
API documentation doesn't load raml file automatically anymore.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#107]
When generating a server, the apidocs doesn't load the raml file automaticly anymore, instead I have a page the ask to load a file from the web or to paste the content of a raml file.
![2016-06-10_1268x463_scrot](https://cloud.githubusercontent.com/assets/303164/15965591/16af1210-2f1f-11e6-83e0-279b20843992.png)

**Comment by iwanbk** [comment]
@zaibon 
There was a change in the apidocs URL, you can go to apidocs page via API home page
https://github.com/Jumpscale/go-raml#simple-home-page-and-api-docs

Steps:

- go to API default home page
- find `API Docs` link there and click it.

**Comment by zaibon** [comment]
Ok found out how the page is loaded. Thanks.
