### ISSUE TITLE
Following readme installation gives a not found error

### ISSUE THREAD

**Issue by mie00** [Jumpscale/go-raml#11]
I tried to follow installation instruction on README.md file. Everything works fine until the code generation part which gives an error on generating both client and server code.

```Asset templates/struct.tmpl not found```

Any idea what is wrong?

**Comment by iwanbk** [comment]
@mie00 
Sorry for the issue, there was some error related to go-bindata. I have fixed it in master, please try again.

**Comment by iwanbk** [comment]
You can find the fix in e07f15ecce45605a109bcc942c5f3724a61b5fec

**Comment by mie00** [comment]
@iwanbk Yes, it worked. Thank you.
