### ISSUE TITLE
Building the generated server using the raml file in raml/samples/congo gives an error

### ISSUE THREAD

**Issue by mie00** [Jumpscale/go-raml#13]
This error appeared on building the generated server
```
./user.go:5: undefined: Date
./user.go:7: undefined: float
```

**Comment by iwanbk** [comment]
@mie00 
sorry for the issue again.
We use custom Date type and missed to include it in the template.

Please try `fix-date` branch and let me know the result

**Comment by mie00** [comment]
@iwanbk 
It now works on the new branch.
Thanks
