### ISSUE TITLE
Fails to generate valid Go for helloworld

### ISSUE THREAD

**Issue by kojustin** [Jumpscale/go-raml#142]
I tried to generate the Go client code based on the [helloworld example](https://github.com/raml-org/raml-examples/blob/master/helloworld/helloworld.raml) in the raml-org/raml-examples project.

```
go-raml client --language go --dir out --ramlfile helloworld.raml 
INFO[2016-08-05T13:15:34-07:00] generating file out/date_only.go             
INFO[2016-08-05T13:15:34-07:00] generating file out/time_only.go             
INFO[2016-08-05T13:15:34-07:00] generating file out/datetime_only.go         
INFO[2016-08-05T13:15:34-07:00] generating file out/datetime.go              
INFO[2016-08-05T13:15:34-07:00] generating file out/datetime_rfc2616.go      
INFO[2016-08-05T13:15:34-07:00] generating file out/struct_input_validator.go 
INFO[2016-08-05T13:15:34-07:00] generating file out/client_utils.go          
INFO[2016-08-05T13:15:34-07:00] generating file out/client_helloworld.go     
ERRO[2016-08-05T13:15:34-07:00] Error running go fmt on 'out/client_helloworld.go' failed:
out/client_helloworld.go:28:79: expected type, found '{'
out/client_helloworld.go:29:3: expected ')', found 'STRING' "title"
out/client_helloworld.go:39:10: expected ';', found '{'
out/client_helloworld.go:52:3: expected declaration, found 'if'
exit status 2
```

go-raml doesn't generate valid code. It takes the example "type" in the RAML file and inserts it function declaration.

```
func(c *Helloworld) HelloworldGet(headers,queryParams map[string]interface{})({
  "title": "Hello world Response",
  "type": "object",
  "properties": {
    "message": {
      "type": "string"
    }
  }
}
 , *http.Response,error) {
        qsParam := buildQueryString(queryParams)
                 var u {
  "title": "Hello world Response",
  "type": "object",
  "properties": {
    "message": {
      "type": "string"
    }
  }
}
```

**Comment by kojustin** [comment]
In general how mature is the go-client code generated by `go-raml`? Should I expect this type of stuff to work?

**Comment by iwanbk** [comment]
@kojustin thanks for this report.

It failed because currently go-raml doesn't handle this kind of definition.
```
       application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "Hello world Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
```

We missed it because this example doesn't exist in [RAML 1.0 spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/).

As an alternative, you can use this definition
```
title: Hello world # required title

/helloworld: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            properties:
                message:
                  type: string
            example: # example how a response looks like
              {
                "message": "Hello world"
              }
```

Which IMHO is better, because not mixing yaml and json.

But of course, it is still a bug that need to be fixed.

```
Should I expect this type of stuff to work?
```

If what you mean by `this type of stuff` is simple .raml, yes it should work.

As comparison, this is [.raml](https://github.com/Jumpscale/go-raml/blob/1480108ba8cbe5c6968deda0ddf32447986d50b6/codegen/fixtures/client_resources/client.raml) we use for unit testing, which is more complex

**Comment by kojustin** [comment]
My question is more general. I'm not sure what to expect from the code generator. RAML 1.0 has many features that are quite advanced (traits, inheritance, etc.). Should I expect traits or inheritance or discriminators to work? What kind of output should I expect and what kind of type safety should I expect? I'm trying to evaluate go-raml for use in a new project.

For instance, I defined a RAML type with an enum and ran `go-raml client` on it, but it was just turned into a `[]string` with no validation. A more natural expression of an enum in go would be a new type and a bunch of `const` declarations.

**Comment by iwanbk** [comment]
```
I'm not sure what to expect from the code generator
```
Thanks for this, we will improve our doc.

```
Should I expect traits or inheritance or discriminators to work?
```
Trait and inheritance should work, discriminator is currently not supported.

```
 What kind of output should I expect and what kind of type safety should I expect?
```
Sorry about lack of documentation on this area, will improve it in #145

```
For instance, I defined a RAML type with an enum and ran go-raml client on it, but it was just turned into a []string with no validation
```
Unfortunately it is expected result now, see https://github.com/Jumpscale/go-raml#type.

```
A more natural expression of an enum in go would be a new type and a bunch of const declarations.
```
will be improved, tracked in #146. Let me know if you have idea about how the code should be generated.

```
 I'm trying to evaluate go-raml for use in a new project.
```
Happy to hear this, let us know what you need and we will do our best .
