### ISSUE TITLE
Generated go client does not allow to override the baseUri

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/go-raml#150]

**Comment by iwanbk** [comment]
@robvanmieghem 

we can override it from where the variable defined because it is a `const`.

example
```
const (
    rootURL = "http://localhost:8080"
)
```

**Comment by robvanmieghem** [comment]
or like this:

https://github.com/itsyouonline/identityserver/commit/007024c69536ced3ab1574bd15d2e55505753a6d

**Comment by iwanbk** [comment]
OK, looks better
