### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#159]
- create an example which generates client/server for golang/python & nim
- do same benchmark for all 3 of them
- print the results, try to optimize the 3 solutions

**Comment by iwanbk** [comment]
@despiegk 
Maybe we can use techempower benchmark first https://www.techempower.com/benchmarks/previews/round13/.

They have done web framework benchmark for years.

There are 2 Nim web frameworks there: nawak & jester.

Both frameworks still have bad results. But please note that it might came from bad test code.

Nawak got better results, but it seems to be not maintained

**Comment by iwanbk** [comment]
@despiegk 

Result so far for benchmarking Go & Nim. Nim is using Jester framework. benchmark tool using: https://github.com/rakyll/boom

summary : 
- Go is faster
- Nim version still failed to decode JSON body from `boom`. But it has no problem to decode JSON body from postman & curl.

```
Benchmark Results

[rakyll/hey]() is used as benchmarking tool.

See the benchmark results below.

## Plaintext

The server endpoint simply return `Hello World!` string.

hey command : `hey -n 30000 -c 50 http://localhost:5000` which means:

- GET request
- number of request : 30K
- number of concurrent request : 50

**Go**

```
Summary:
  Total:    1.5014 secs
  Slowest:    0.0539 secs
  Fastest:  0.0001 secs
  Average:    0.0024 secs
  Requests/sec: 19981.8522
  Total data: 360000 bytes
  Size/request: 12 bytes
```

**Nim**

```
Summary:
  Total:    2.1525 secs
  Slowest:    0.0435 secs
  Fastest:  0.0002 secs
  Average:    0.0036 secs
  Requests/sec: 13937.1186
  Total data: 360000 bytes
  Size/request: 12 bytes
```

## Returns JSON

The server endpoint returns JSON array

hey command : `hey -n 30000 -c 50 http://localhost:5000/users`

**Go**
```
Summary:
  Total:    1.6139 secs
  Slowest:    0.0440 secs
  Fastest:  0.0001 secs
  Average:    0.0026 secs
  Requests/sec: 18588.8480
  Total data: 990000 bytes
  Size/request: 33 bytes
```

**Nim**

```
Summary:
  Total:    2.1811 secs
  Slowest:    0.0441 secs
  Fastest:  0.0001 secs
  Average:    0.0036 secs
  Requests/sec: 13754.6201
  Total data: 1050000 bytes
  Size/request: 35 bytes
```

## Decode JSON

The endpoint decode a JSON string and response with plain string

command : `hey -n 30000 -c 50 -m POST -d '{"name":"John", "username": "Doe"}'  http://localhost:5000/users`

**Go**

```
Summary:
  Total:    3.4145 secs
  Slowest:    0.0436 secs
  Fastest:  0.0002 secs
  Average:    0.0055 secs
  Requests/sec: 8786.1079
  Total data: 210000 bytes
  Size/request: 7 bytes
```

**Nim**
Failed to decode, with this error

Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 400 Bad Request\r\nContent-Length: 31\r\n\r\nBad Request. No Content-Length."; err=<nil>

```

**Comment by iwanbk** [comment]
`ab` also failed for Nim

```
#ab -n 30000 -c 50 -p /tmp/data.json -T 'application/json' http://localhost:5000/users
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_socket_recv: Connection refused (61)
```

**Comment by iwanbk** [comment]
@despiegk @zaibon 
About Nim was slower than Goi think it is because Nim only use 1 core, while Go can use all cores.

i have confirmed it with:
- setting Go to only use 1 cpu
- do the benchmark in 1 CPU VM

i'll post update benchmark result after fix the issue about Jester failed to decode request from `ab` & `hey`

**Comment by iwanbk** [comment]
```
Jester failed to decode request from ab & hey
```
I think i found the issue.
Nim asynchttpserver doesn't have `Transfer-Encoding: chunked` http request.

Code : https://github.com/nim-lang/Nim/blob/devel/lib/pure/asynchttpserver.nim#L176

I can use https://github.com/tarekziade/boom to do benchmark, but still not sure about the result because Nim, Go 1 core, and Go all cores got very similar results. While hey & ab gave different

**Comment by iwanbk** [comment]
I managed to make `ab` to work with Nim in POST request, we should use `127.0.0.1` instead of `localhost`.
But result from `ab` is not consistent, unlike result from `hey`
