### ISSUE TITLE
Update and any timelines?

### ISSUE THREAD

**Issue by sichvoge** [Jumpscale/go-raml#162]
Hi. This project is awesome and very helpful. Where are you guys and whats your timelines for the final release of the project? Can I contact you somehow over PM?

**Comment by iwanbk** [comment]
@sichvoge feel free to contact me.

**Comment by andjarnic** [comment]
@iwanbk not sure how to contact you here on Github, would like to discuss RAML 1.0 support for Go being broken out into a separate project with you. I would also like to understand the RAML to microservice generation, with support for RAML 1.0 Types, libraries, etc.  What is the best way to contact you?

**Comment by iwanbk** [comment]
@andjarnic iwanbk - gmail

**Comment by robvanmieghem** [comment]
@sichvoge If you want we can always set up a video call

**Comment by iwanbk** [comment]
@andjarnic : @robvanmieghem is better person to call than me.

**Comment by sichvoge** [comment]
@robvanmieghem would be happy to set up a video call with you. let me send you an email.

**Comment by kevinduffey** [comment]
@robvanmieghem @sichvoge please let me know if I may join. I would like to take part in this project, at the very least learn/test/use but if time allows (and my Go coding skills improve vastly) help contribute.
