### ISSUE TITLE
raml spec for https://my.zerotier.com/help/api

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#165]
- create raml spec for zerotier
- create a script to generate python client for it
- dome some tests in creating network
- all fully documented
- put in examples/zerotier_client

**Comment by despiegk** [comment]
maybe can use: https://github.com/mulesoft/swagger-to-raml-object ?
make sure output is clean & documented though !

or 
https://github.com/8x8Cloud/swagger2raml

or

https://github.com/lucybot/api-spec-converter

**Comment by despiegk** [comment]
if https://github.com/8x8Cloud/swagger2raml works or other tool
please create docker (buildfile) which allows easy conversion without installing tools

**Comment by iwanbk** [comment]
https://github.com/mulesoft/swagger-to-raml-object only support swagger 1.2

https://github.com/8x8Cloud/swagger2raml got exception

https://github.com/lucybot/api-spec-converter doesn't support converting to .raml

https://github.com/swagger-api/swagger-codegen is the best choice now

**Comment by iwanbk** [comment]
implemented in https://github.com/g8os/zerotier_client
