### ISSUE TITLE
No python generator support for properties with interpolation. Inflectors cause misidentification as union.

### ISSUE THREAD

**Issue by jasco** [Jumpscale/go-raml#205]
The use of interpolated parameters as in the following sample appears to be unsupported.  Is this on the roadmap?

```
resourceTypes:
  collection:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                <<resourcePathName|!pluralize>>: <<resourcePathName|!uppercamelcase|!singularize>>[]

```

Interestingly the generator reports an error `validator has no support for union, ignore it`.  The python field generator searches for "|" in the type and identifies it as a union.

**Comment by jasco** [comment]
I think the interpolation is supposed to have happened in the raml parser but it is not immediately obvious to me where the properties are parsed.

**Comment by iwanbk** [comment]
i think it is fixed by #204?

**Comment by jasco** [comment]
Unfortunately, no.  The issue seems to be that there is no parameter interpolation for these elements.  It also affects the go-generator but with a somewhat less ambiguous error.

> Error running go fmt on 'outgo/UsersGetRespBody.go' failed:
> outgo/UsersGetRespBody.go:11:9: expected '}', found '<<'
> outgo/UsersGetRespBody.go:25:5: expected declaration, found 'return'

The generate code clearly shows the raw parameter name:

```
type UsersGetRespBody struct {

        <<ResourcePathName|!Pluralize>>   []interface{} `json:"<<resourcePathName|!pluralize>>" validate:"nonzero"`
}
```

**Comment by iwanbk** [comment]
@jasco i pushed a fix on `fix-method-properties-inheritance` branch. Let me know if it fixes your issue

**Comment by jasco** [comment]
Yes, this issue is fixed!  Thank you!  It generates to completion now.
