### ISSUE TITLE
bad_raml test failing with numeric value cannot be of type string

### ISSUE THREAD

**Issue by jasco** [Jumpscale/go-raml#206]
Current master 6e4868b raml tests have failure:

Attempting to parse RAML file: ./samples/bad_raml.raml
line 43: cannot unmarshal !!str `hello` into int
source:  string
Detected bad RAML file ./samples/bad_raml.raml:
Error parsing RAML:
  line 43: numeric value cannot be of type string (got `hello`), must be integer
Attempting to parse RAML file: ./samples/congo/api.raml
Successfully parsed file ./samples/congo/api.raml!

**Comment by iwanbk** [comment]
hi @jasco 
i don't see any problem here.

The test intended to test the parser ability to detect bad .raml file.

**Comment by jasco** [comment]
@iwanbk you're correct. I just came back because I finally realized the same thing.
