### ISSUE TITLE
Generate python class from RAML types

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#210]
we currently only generate flask-wtf class for request body validation.

**Comment by razor-1** [comment]
We have an implementation of this. It's not ready for a PR yet but it does generate python classes based on RAML types and provides a nice to work with interface to the types, and generates a client from requests that sets up query parameters defined on the methods, etc.

**Comment by iwanbk** [comment]
@razor-1 
cool. 
Can you give example on how the class look like?
Where i can see your implementation?

**Comment by razor-1** [comment]
@iwanbk you can check out the [python-client](https://github.com/razor-1/go-raml/tree/python-client) branch of my fork.

**Comment by iwanbk** [comment]
@razor-1 
i've tried it and the generated class looked good.
when will it is ready for a PR?
Is there something i can help?

**Comment by razor-1** [comment]
@iwanbk thank you. Right now there aren't any tests against this so we need those probably before a PR.  If you want to adapt the current fixtures for this it would be great.  I also have a small patch I can put in for python3 support.

**Comment by iwanbk** [comment]
```
If you want to adapt the current fixtures for this it would be great
```
Sure, i can add it after the PR merged
```
I also have a small patch I can put in for python3 support.
```
That's cool

**Comment by iwanbk** [comment]
@razor-1 
i tried your branch to generate python class for `docs/tutorial/api.raml`
i think we can improve it a bit to be like this
```
import json

class User(object):
    @staticmethod
    def create(username=None, name=None):
        return User(
            username=username,
            name=name
            )
    
    def __init__(self, **kwargs):
        name = kwargs.get("name")
        if name:
            self.name = name

        username = kwargs.get("username")
        if username:
            self.username = username
    
    def to_json(self):
        return json.dumps(self.__dict__)

user = User.create(username="ibk")

print(user.to_json())
```

it still missed type checking, but seems on a good way.

**Comment by iwanbk** [comment]
implementation plan.

step 1,  basically like the above code:
- [ ] provide static method to create the object, required field must be non optional argument
- [ ] provide `to_json` method to create json representation
- [ ] create object from json

step 2, basic validation
- [ ]check if user supplied valid datatypes for each field

step 3, advanced validation
- [ ] check for min/max length, min value, etc...

@razor-1 
i can see that your branch already implement the step 1 & 2, it would be great to receive your PR.
If not, we need it now, so we will implement it.

**Comment by razor-1** [comment]
OK let me get our latest changes and get a PR in ASAP
