### ISSUE TITLE
generate python asyncio server & client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#211]
- generate code using python asyncio server
- create client as well
- do small example
- integrate with JWT & IYO

**Comment by despiegk** [comment]
also needs #212

**Comment by iwanbk** [comment]
for the client, it seems that `aiohttp` is good enough.

For the server, i found `aiohttp` and `https://github.com/channelcat/sanic`.

`aiohttp` perform poorly when encoding json response, slower than Django and Flask
http://klen.github.io/py-frameworks-bench/
The benchmark was done at Jul 2016, i'll check if `aiohttp` got improvement.

While sanic is relatively new, not much info i can find.

**Comment by iwanbk** [comment]
I did benchmark between aiohttp, sanic, Go with 1 CPU, and Go with 2 CPU.

It benchmarked two cases:
- server returns plain text
- server returns JSON response

It is subset of  benchmark we did with Go, Nim, and Flask.

Results summary from number of requests/second:
- aiohttp is 4x slower than sanic
- sanic speed is 12%-30% slower than Go with 1 proc

**Comment by iwanbk** [comment]
Sanic also has similar API with Flask, make it easier to learn.

So, i think we should use Sanic for the server part.

**Comment by iwanbk** [comment]
benchmark results:

Plain text (hello word)

```
-- aiohttp

Summary:
  Total:	18.1614 secs
  Slowest:	0.4182 secs
  Fastest:	0.0014 secs
  Average:	0.0301 secs
  Requests/sec:	1651.8527
  Total data:	360000 bytes
  Size/request:	12 bytes

-- Sanic

Summary:
  Total:	3.2828 secs
  Slowest:	0.0336 secs
  Fastest:	0.0003 secs
  Average:	0.0054 secs
  Requests/sec:	9138.6268
  Total data:	360000 bytes
  Size/request:	12 bytes

-- Go 1 proc

Summary:
  Total:	2.9199 secs
  Slowest:	0.0417 secs
  Fastest:	0.0002 secs
  Average:	0.0048 secs
  Requests/sec:	10274.3559
  Total data:	360000 bytes
  Size/request:	12 bytes

Go 2 procs

Summary:
  Total:	2.0668 secs
  Slowest:	0.0269 secs
  Fastest:	0.0002 secs
  Average:	0.0034 secs
  Requests/sec:	14515.2946
  Total data:	360000 bytes
  Size/request:	12 bytes
```

JSON response

```
-- aiohttp

Summary:
  Total:	17.8108 secs
  Slowest:	0.4131 secs
  Fastest:	0.0011 secs
  Average:	0.0295 secs
  Requests/sec:	1684.3701
  Total data:	1050000 bytes
  Size/request:	35 bytes

 -- Sanic

 Summary:
  Total:	3.6667 secs
  Slowest:	0.0257 secs
  Fastest:	0.0004 secs
  Average:	0.0061 secs
  Requests/sec:	8181.8411
  Total data:	960000 bytes
  Size/request:	32 bytes

Go 1 Proc

Summary:
  Total:	2.5927 secs
  Slowest:	0.0253 secs
  Fastest:	0.0002 secs
  Average:	0.0042 secs
  Requests/sec:	11571.0427
  Total data:	990000 bytes
  Size/request:	33 bytes

Go 2 Proc

Summary:
  Total:	1.8725 secs
  Slowest:	0.0265 secs
  Fastest:	0.0002 secs
  Average:	0.0031 secs
  Requests/sec:	16020.9706
  Total data:	990000 bytes
  Size/request:	33 bytes
```

**Comment by iwanbk** [comment]
I tried aiohttp with uvloop as event loop engine.
uvloop make it 1.5x faster, but still lot slower than sanic.

aiohttp with uvloop

plain text
```
Summary:
  Total:	14.0147 secs
  Slowest:	0.0530 secs
  Fastest:	0.0010 secs
  Average:	0.0233 secs
  Requests/sec:	2140.6071
  Total data:	360000 bytes
  Size/request:	12 bytes
```
json response
```
Summary:
  Total:	15.4557 secs
  Slowest:	0.0733 secs
  Fastest:	0.0011 secs
  Average:	0.0257 secs
  Requests/sec:	1941.0369
  Total data:	1050000 bytes
  Size/request:	35 bytes
```

**Comment by iwanbk** [comment]
as for http client, aiohttp is still the only choice.
I still look a way to create good http client lib with it.

**Comment by iwanbk** [comment]
the benchmarked servers code
https://gist.github.com/iwanbk/62b90593dc3500b5243db27ac52d01db

**Comment by iwanbk** [comment]
current progress, implemented things:
- main file
- route
- api skeleton
- apidocs
- oauth2 jwt

tomorrow:
- bug fix
- jsonschema for request body validation
- fix things marked as `TODO`

works can be found at `asyncio` branch

I attached generated code for tutorial .raml file https://github.com/Jumpscale/go-raml/blob/master/docs/tutorial/api.raml

to generate it, please add `--kind sanic` options, sample command:
```
go-raml server -l python --ramlfile docs/tutorial/api.raml --dir /tmp/sanic --kind sanic
```
[sanic.tar.gz](https://github.com/Jumpscale/go-raml/files/716555/sanic.tar.gz)

**Comment by iwanbk** [comment]
update:
- add [python jsonschema](https://pypi.python.org/pypi/jsonschema) for request validation. It only support these:
    - scalar type
    - array of scalar type
    - plain object (without union, inheritance, composition, etc)

next:
   - add unit tests
   - docs
   - code cleanup, especially regarding duplication with flask part.

quick doc:
   - oauth2 jwt itsyouonline integration need same step as flask version
   - to generate it, please add `--kind sanic` option

**Comment by iwanbk** [comment]
update:

Server:
- add unit test 
- add docs 
- add example

server todo:
- json schema improvements
- libraries support: not in near time, except really needed

client:
- implemented it using aiohttp

client todo:
- more tests, currently only tested using tutorial's raml
- add unit test
- docs
