### ISSUE TITLE
generate gevent based client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#212]
also generate client for gevent
- this is needed in jsportal because there we use gevent
- this gevent based client needs to be able to connect to any server we have using goraml

**Comment by iwanbk** [comment]
@despiegk 
Which library we should use?
I found `geventhttpclient` and `grequests` and prefer `grequests` for API familiarity.

**Comment by grimpy** [comment]
Why do we need this? Go raml uses requests. If your gevent application patches socket and dns properly at the beginning this should work perfectly.
The portal already does this so it should just work out of the box.

See: first 8 lines of https://github.com/Jumpscale/jumpscale_portal8/blob/master/apps/portalbase/portal_start.py

**Comment by iwanbk** [comment]
i've just checked `grequests`, it only provide helper for `requests` to work with gevent.

```
The portal already does this so it should just work out of the box.
```
because the portal already did this, we might not need this helper.
