### ISSUE TITLE
Create an Angular2 client

### ISSUE THREAD

**Issue by mie00** [Jumpscale/go-raml#221]
There is already a lot of [scaffolding tools for angular2](http://stackoverflow.com/questions/29649578/available-yeoman-generator-for-angular-2#29844571).

So it would be useful if we can generate an Angular2 client using go-raml.

**Comment by iwanbk** [comment]
@mie00 
i have played with angularjs few years ago, but only for simple use case.

Do you which tool that is best for our use case?
And how far it can help? Can we build a complete client by using that tool?

**Comment by mie00** [comment]
I think we can use [the official angular scaffolding tool](https://github.com/angular/angular-cli) to create a minimal app.Then I can create go-raml templates based on that. I make a pull request once it is done.

The problem is, there will be more than 20 file, some of them are static. Is there a way to put them in a separate directory under templates, to avoid the confusion between templates for other clients/servers. Also can we make a separation between how we add static files and templates.

So for example:
```
templates
|_ Angular2
   |_ static
      |_ <files that will be copied as is>
   |_ templates
      |_<files that will be inserted dynamically>
```

**Comment by iwanbk** [comment]
```
The problem is, there will be more than 20 file, some of them are static. Is there a way to put them in a separate directory under templates, to avoid the confusion between templates for other clients/servers
```
sorry, why we need those templates?
I thought that the scaffolding tool will generate the file for us?

```
Also can we make a separation between how we add static files and templates.
```
it is a good idea.

**Comment by mie00** [comment]
We can use one to create a boilerplate to work on, or we can use it during runtime to generate one for us.

The problems with the first option are:

1. Bigger go-raml binary size.
2. We will have to apply changes manually in order to make use of an updated scaffolding tool.

The problems with the second option are:

1. It will be harder and more fragile trying to alter files that are already generated than using a template.
2. The user has to have the tool preinstalled alongside node.js and npm.
3. The tool has the same version as what we used for development, to guarantee that the generated files look like what we expect.

What I see is that choosing the first option will be a lot easier and with almost the same results. What do you think?

**Comment by iwanbk** [comment]
@mie00 
i prefer second option for these reasons:
-  first option need lot of time to keep updated

as you mentioned
'''
We will have to apply changes manually in order to make use of an updated scaffolding tool.
'''

- about need to install the tool

```
The user has to have the tool preinstalled alongside node.js and npm.
```
I think it is normal for the user to have the tool installed.
because there might be tool's features that is not supported by go-raml, simply because it is not covered by RAML.

User likely have latest tool, and it might create conflict if we don't support that latest one.

**Comment by mie00** [comment]
Go-raml shouldn't force users to have another code generation tool to be installed.
Also because we'll be hacking the generated code. The scaffolding tool itself (not node, npm) has to be the same version that we used during development to make sure that our hack-ish way works.
Also blindly hacking generated code will always be fragile, hard to maintain than using our templates (originally generated by the same tool).

Above that, all of the scaffolding tools that I have seen doesn't provide much, most of them (including the official one) only generate useless templates (services, components, etc.).

So if we want to use another scaffolding tool to generate our templates during runtime, maybe we can use our templates to get it working first and then migrate to the other tool later.
