### ISSUE TITLE
In GO, generated server code should take care of setting correct content-type header

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/go-raml#237]
The generated server code, should have the necessary lines to correctly set the `content-type ` to `application/json` by default.

Also the lines where it says 
```go
// uncomment below line to add header
// w.Header().Set("key","value")
```
Should actually be `ABOVE` the body writing, since u can't write the headers after the body has been written.

**Comment by robvanmieghem** [comment]
You are right @muhamadazmy to generate the setting of the content-type, I would even drop the commented example of setting an extra header.

**Comment by iwanbk** [comment]
@robvanmieghem @muhamadazmy 
I have two points of view here:
- each method usually has many places that returning a response. Developers usually (at least in my previous projects) write few functions to write the response, this is the place where they write the code to set content-type.

- we can add the code as an example

**Comment by zaibon** [comment]
I agree with Azmy, go-raml should set the content type.
User can still modify the header is needed. But the generated code should have as much boilerplate code as possible.

**Comment by iwanbk** [comment]
ok, will do it
