### ISSUE TITLE
Array declaration in go code has wrong format.

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#24]
Extract of the raml file
```raml
responses:
      200:
      body:
           application/json:
            type: Namespace[]
```

Generated Go code
```go
var respBody Namespace[]
```

Go code is not valide, it should be
```go
var respBody []Namespace
```

**Comment by iwanbk** [comment]
@zaibon thanks for this report, i will check it.

**Comment by iwanbk** [comment]
@zaibon 
I am not sure if your use case is valid RAML 1.0 syntax.

From my understanding, we can only define new type using [Types](http://docs.raml.org/specs/1.0/#raml-10-spec-types).

So, you need to define new type, and then use that type in response body.

But of course i could be wrong, i will read the spec again.

**Comment by zaibon** [comment]
Indeed, if I declare the array in types section and the use it, it works without problem.
Probably a wrong interpretation of the specs from myself.

**Comment by iwanbk** [comment]
@zaibon 
i have read it again, i still think that  your syntax is not valid

**Comment by zaibon** [comment]
You're right, I close.
