### ISSUE TITLE
Parser doesn't support 'Shortcuts and Syntactic Sugar'

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#25]
From the raml specs http://docs.raml.org/specs/1.0/#raml-10-spec-shortcuts-and-syntactic-sugar

it should be possible to write something like :
```raml
Namespace:
    type: object
    properties:
        name:
           type: string
```

in a shorter form
```raml
Namespace:
    properties:
        name: string
```

But the parser outputs error when trying to deal with the short form
```
line 19: cannot unmarshal !!str `string` into raml.Property
source:  string
ERRO[2016-02-23T10:31:41+01:00] Error parsing RAML:
  line 19: raml.Property cannot be of type string (got `string`), must be 
```

**Comment by iwanbk** [comment]
@zaibon 
Shortcut and syntaxtic sugar is actually in the limitation https://github.com/Jumpscale/go-raml/blob/master/docs/limitations.md

But i will work on it tomorrow, look like i will have some spare time tomorrow.

**Comment by zaibon** [comment]
Indeed, my bad didn't see the limitations.

**Comment by robvanmieghem** [comment]
Is noted in the [limitations](https://github.com/Jumpscale/go-raml/blob/master/docs/limitations.md) but it would be great if Iwan could add some (like the required: false shortcut)

**Comment by iwanbk** [comment]
@zaibon 
I have tried to support this kind of syntax
```
Email: string
```
But still failed, 

To support above syntax, property must support plain string & raml.Property( current property type).
So, i defined it as `interface{}` and then cast it. But it always detected as string.
I will check it when possible. 


@robvanmieghem 
```
like the required: false shortcut
```
btw,  `required=false` by default.

this `nick?: string` syntax also face same issue as `Email: string` i described above.

**Comment by iwanbk** [comment]
i have some idea about this, i will try it tomorrow.

**Comment by iwanbk** [comment]
syntactic sugar & shortcut support added at PR #28 in 5147ae9dd1c989756cd8b9b7f080d1e0eae0e744
