### ISSUE TITLE
Generated python client does not support multipart/form-data

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/go-raml#265]
See https://github.com/g8os/grid/blob/1.1.0-alpha/raml/api.raml#L485

Atleast make it possible to pass *args and **kwargs to the python requests directly so we can manully access files kwarg.
Also remove https://github.com/Jumpscale/go-raml/blob/python-inheritance/codegen/templates/client_python.tmpl#L11
This is not needed requests will automaticly add this header then json kwargs is used and makes it absolutly impossible to overwrite this header properly.

**Comment by iwanbk** [comment]
@robvanmieghem are you sure about `type_bug` label? go-raml was built with `application/json` in mind.
If it supposed to also support other content type, then:
- we need to fix other languages
- we need to update the parser.

With #262 and previous PR related to types, the work shouldn't be very big.
