### ISSUE TITLE
invalid code generation for built-in go type as request body

### ISSUE THREAD

**Issue by GlenDC** [Jumpscale/go-raml#268]
When generating code from a spec which uses a built in type (`string`) (or slice of any kind of type (`[]Foo`, `[]string`) as the request body, the generated code is invalid. This because it seems to simply lowercase the type and use that as the name of the variable, which of course doesn't work when working with a builtin type or slice.

Example:

```raml
          post:
            (AYSBased):
            displayName: CreateStoragePoolDevices
            description: Add extra devices to this storage pool
            body:
              application/json:
                description: List of devices to add to the storage pool
                type: string[]
                example: ['/dev/sdc', '/dev/sdd']
            responses:
              204:
                description: Devices added successfully
```

(source: https://github.com/g8os/grid/blob/1.1.0-alpha/raml/api.raml#L272-L283)

will result in:

```go
// Add extra devices to this storage pool 
func (s *NodesService) CreateStoragePoolDevices(storagepoolname, nodeid string, []string []string, headers,queryParams map[string]interface{})(*http.Response,error) {
		

        resp, err := s.client.doReqWithBody("POST", s.client.BaseURI + "/nodes/"+nodeid+"/storagepools/"+storagepoolname+"/devices", &[]string, headers, queryParams)
		if err != nil {
			 return nil, err}
		defer resp.Body.Close()

		
			return resp, nil
}
```

Which obviously doesn't make any sense. I think it would be much better to simply use `body` as a variable name, in which the above generated code would become:

```go
// Add extra devices to this storage pool 
func (s *NodesService) CreateStoragePoolDevices(storagepoolname, nodeid string, body []string, headers,queryParams map[string]interface{})(*http.Response,error) {
		

        resp, err := s.client.doReqWithBody("POST", s.client.BaseURI + "/nodes/"+nodeid+"/storagepools/"+storagepoolname+"/devices", &body, headers, queryParams)
		if err != nil {
			 return nil, err}
		defer resp.Body.Close()

		
			return resp, nil
}
```

I have at the moment zero knowledge of the go-raml codebase though, so I might be missing some complexity here. But this issue is blocking me at the moment to resolve https://github.com/g8os/blockstor/issues/60, as the new grid api raml triggers this issue.

**Comment by iwanbk** [comment]
Thanks for the report @GlenDC 
```
I have at the moment zero knowledge of the go-raml codebase though, so I might be missing some complexity here
```
it shouldn't be complex.

**Comment by GlenDC** [comment]
Ah cool, @iwanbk :) Was going to fix it myself right now, but I see you fixed it already, so thank you!
