### ISSUE TITLE
python: handle case where property use python reserved keyword as it's name

### ISSUE THREAD

**Issue by RubenMattan** [Jumpscale/go-raml#275]
```python
Transaction:
    properties:
      from:
        type: string
        displayName: from_


property_name = 'from'
val = data.get(property_name)
if val is not None:
    datatypes = [str]
    try:
        self.from = client_support.val_factory(val, datatypes)
    except ValueError as err:
        raise ValueError(create_error.format(cls=class_name, prop=property_name, val=val, err=err))
    else:
        raise ValueError(required_error.format(cls=class_name, prop=property_name))
```

**Comment by iwanbk** [comment]
@RubenMattan i can't find in the spec that type's property could have `displayName`.
Can you point me please?

**Comment by RubenMattan** [comment]
Hello,

Well i saw it in the api workbench in Atom. But i think this is the spec https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#type-declarations

**Comment by iwanbk** [comment]
> But i think this is the spec https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#type-declarations

It is for `Type`, while what we need is for `Property` https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#property-declarations

**Comment by RubenMattan** [comment]
Okey, well i have a property named 'from' but its a reserved keyword in python...

**Comment by RubenMattan** [comment]
Yes i was planning to do the same :-)

**Comment by iwanbk** [comment]
We also need to do the same with Go & Nim.
Nim already did some handling, but still need to be improved.

**Comment by iwanbk** [comment]
This is not as simple as expected, because if we append with `_`,  the JSON field will also changed.

**Comment by iwanbk** [comment]
By @RubenMattan helps, we will modify the class to be something like

https://github.com/rogerthat-platform/paycash-api-client/blob/e1538707881657c9f244b452a75314ab246b5210/paycashapiclient/Transaction.py#L14-L27

and 

https://github.com/rogerthat-platform/paycash-api-client/blob/e1538707881657c9f244b452a75314ab246b5210/paycashapiclient/Transaction.py#L65-L67
