### ISSUE TITLE
Upload file method in container with parameters as description , give bad request 

### ISSUE THREAD

**Issue by Dinaamagdy** [Jumpscale/go-raml#297]
## Method:
method :  POST /nodes/{nodeid}/containers/{containername}/filesystem

## Request:
![selection_364](https://cloud.githubusercontent.com/assets/24386802/26550140/abd55250-447c-11e7-9d0f-5d19a575e9b1.png)

## Response:
![selection_365](https://cloud.githubusercontent.com/assets/24386802/26550278/350eecde-447d-11e7-8d61-4c944d8ea70f.png)

### how should I use it ? 
I think the problem in data parameter as in python requests the body should be named as files

**Comment by iwanbk** [comment]
> how should I use it ?

@grimpy might be able to help

**Comment by zaibon** [comment]
This doesn't looks like a go-raml issue.
