### ISSUE TITLE
Go-raml deletes essential parameters from client methods in generation

### ISSUE THREAD

**Issue by khaledkbadr** [Jumpscale/go-raml#302]
When running `go-raml client -l python --dir pyclient/zeroos/orchestrator/client/ --ramlfile raml/api.raml` to [api.raml](https://github.com/zero-os/0-orchestrator/blob/master/raml/api.raml) 

It removed essential parameters like data in Fileupload [here](https://github.com/zero-os/0-orchestrator/pull/354/commits/61583a1d8923e6c8730e64587a6a42f9026fb494#diff-bb205d9cb8e92f96e1d3f2fb3d7adcddL79)

**Comment by iwanbk** [comment]
Fixed at #307.
It was caused by regression of #283
