### ISSUE TITLE
cannot generate zerotier client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#315]
## case 1

https://github.com/Jumpscale/howto_api/tree/master/raml/zerotier_example_converted

## case 2

https://github.com/Jumpscale/howto_api/tree/master/raml/manualspec_includes

**Comment by iwanbk** [comment]
> case 1

Fixed in `fix-zerotier` branch

> case 2

still checking, the parser seems failed to load the included files properly

**Comment by iwanbk** [comment]
fixes for `case 1` (and some part of case 2) has been merged to master at #319.

Fixes for `case 2` will be done in another PR because it is quite different case.

Case 2 is about resource types while case 1 is about "items" declaration
