### ISSUE TITLE
Error generating go server - YAML

### ISSUE THREAD

**Issue by mchacon-ml** [Jumpscale/go-raml#316]
Hi!!
I am trying to generate a GO server based on the tutorial-jukebox-api definition but I am getting this error:

INFO[2017-09-11T07:16:32-03:00] Generating a go server                       
INFO[2017-09-11T07:16:32-03:00] API file per method=false                    
ERRO[2017-09-11T07:16:32-03:00] Error parsing RAML:
  yaml: control characters are not allowed

Is there any workaround to support it or are you going to support this kind of definition?

Thanks!
masch

**Comment by iwanbk** [comment]
@mchacon-ml thanks for the report.

could you provide us the .raml you use?

**Comment by mchacon-ml** [comment]
Yes, sure: 
https://github.com/raml-org/raml-tutorial-200/blob/master/jukebox-api.raml

Thanks!

**Comment by iwanbk** [comment]
@mchacon-ml 
I found that the issue is on this line `!include heybulldog.mp3`, the parser should ignore this kind of file
