### ISSUE TITLE
python: 'datetime' not imported for generated objects

### ISSUE THREAD

**Issue by lucasvanhalst** [Jumpscale/go-raml#317]
For example: https://github.com/itsyouonline/identityserver/blob/master/clients/python/itsyouonline/DigitalAssetAddress.py#L68

I think it should be `client_support.datetime` instead

**Comment by iwanbk** [comment]
> I think it should be client_support.datetime instead

Why not `import datetime`? 
Because i don't see that `client_support` has it's own `datetime` type

**Comment by iwanbk** [comment]
> Why not import datetime?
> Because i don't see that client_support has it's own datetime type

Just tested it, both solutions are working

**Comment by iwanbk** [comment]
@lucasvanhalst fixed it on #321, please check, the changes you needed:
- the .raml https://github.com/Jumpscale/go-raml/pull/321/files#diff-2510b20174cbda3912884b63d2c96b0bR129
- generated file : https://github.com/Jumpscale/go-raml/pull/321/files#diff-1494b856c0945fba8ab201dadd0dba51, it added `from datetime import datetime`
