### ISSUE TITLE
Returns actual type instead of http response

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#318]
Currently when generating a python client, the methods return `response` object on which we need to execute `content` or `json` or other method like that.

I would be nice if instead of returning a `response` object the method returns an object of the type that the method actually returns.
For example a method  that would return a json body like this:
```json
{
   "id": "myid",
   "data": "hello world"
}
```
Would return a object with the `id` and `data` property. In case of failure, an exception that contain the http response would be raise, so we can still inspect it.

Go-raml already support the generation of these types, so I don't think that would be a lot of work to implement this feature.

**Comment by despiegk** [comment]
should be as an option then we can choose

**Comment by iwanbk** [comment]
If we do this, we have similar issue as https://github.com/Jumpscale/go-raml/issues/330#issuecomment-342056559.
What the generated code looks like if the API has many response codes?
Because each response code might have different object

**Comment by zaibon** [comment]
In most cases I don't think a endpoint has many different valid response types.
Of course you can have different response if your call fails, or if the request is invalid, but these are not normal cases. And with what I propose, we still return a valid http response object that user can inspect as he wants

**Comment by iwanbk** [comment]
ah OK, i missed 

> an exception that contain the http response would be raise, so we can still inspect it.

**Comment by iwanbk** [comment]
WIP can be found on `python-client-unmarshal-resp` branch.

example of the generated file : https://github.com/Jumpscale/go-raml/blob/python-client-unmarshal-resp/codegen/python/fixtures/client/requests_client/unmarshall_response/users_service.py

when failed to unmarshall, it raise this exception https://github.com/Jumpscale/go-raml/blob/python-client-unmarshal-resp/codegen/python/fixtures/client/requests_client/unmarshall_response/unmarshall_error.py
