### ISSUE TITLE
Extra encoding/json import

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#328]
Generating a go client from a raml file adds an "encoding/json" import even if it is not used in the file.
Example:
Generate go client from this file https://github.com/Jumpscale/ays9/blob/master/JumpScale9AYS/ays/server/apidocs/api.raml
The generated file webhooks_service.go will contain this unused import.

**Comment by iwanbk** [comment]
`encoding/json` is always included in current template

https://github.com/Jumpscale/go-raml/blob/2fd13b284124d235f8b66f9b95b1eb05b4661b89/codegen/templates/client_service_go.tmpl#L5-L7

Should add some checks
