### ISSUE TITLE
generated go client doesn't properly support responses with different status code

### ISSUE THREAD

**Issue by LeeSmet** [Jumpscale/go-raml#339]
The generated go client always seems to assume the response type from the first response. e.g.:

RAML:
```raml
 /owners:
      securedBy: [oauth_2_0: { scopes: [ "organization:owner" ] } ]
      post:
        displayName: AddOrganizationOwner
        description: Invite someone to become owner of an organization.
        body:
          application/json:
            type: Member
        queryParameters:
          invitenotification?:
            type: string
            description: Set to `none` to suppress sending an sms or email
        responses:
          201:
            description: Invite created successfully
            body:
              application/json:
                type: JoinOrganizationInvitation
          404:
            description: The user or the organization does not exist.
          409:
            description: The user already is an owner.
```

Generated code:
```go
// Invite someone to become owner of an organization.
func (s *OrganizationsService) AddOrganizationOwner(globalid string, body Member, headers, queryParams map[string]interface{}) (JoinOrganizationInvitation, *http.Response, error) {
	var u JoinOrganizationInvitation

	resp, err := s.client.doReqWithBody("POST", s.client.BaseURI+"/organizations/"+globalid+"/owners", &body, headers, queryParams)
	if err != nil {
		return u, nil, err
	}
	defer resp.Body.Close()

	return u, resp, json.NewDecoder(resp.Body).Decode(&u)
}
```

The problem here is that the client does not look up the status code itself. It returns by always trying to decode the response body. If the 404 or 409 status code get returned (or 401/403 by the security middleware, not included in the raml fragment), the client seemingly returns nothing. If the server also returns a status text (either the string representation of the code or something custom, e.g.: 404 -> Not found), the client returns an error because this is not valid json. This is often the case when the server returns a 4xx (or 5xx) status code throught go's `http.Error` function, e.g.: `http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound)`. I feel like the generated client should ignore the body in this case since no return body is declared in the raml file

### summary

- The client does not handle responses well if multiple are defined in the raml and 1 has a body and the other one does not 
- (Not sure if this is an actual issue or a design choice) If you use the client, you must manually inspect the returned http response to check the status code and act accordingly.

**Comment by iwanbk** [comment]
Thx @LeeSmet , it might be a known issue, on which i have solution proposal at https://github.com/Jumpscale/go-raml/issues/330#issuecomment-341419304

Let me know your thought there.

**Comment by iwanbk** [comment]
> (Not sure if this is an actual issue or a design choice) If you use the client, you must manually inspect the returned http response to check the status code and act accordingly.

This is my proposal, which we can't do properly now because response body already consumed by json encoder.

I don't propose to handle each status code because:
- there might be many status codes, then the API will return too many values, which is ugly.
- some error condition might not be declared properly in .raml

**Comment by LeeSmet** [comment]
I see, given these points, I think this can indeed be moved to the discussion in #330
