### ISSUE TITLE
Make python client passed pep8 check

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#355]
Make it pass this check tool https://pypi.python.org/pypi/pep8

blocked by #353

**Comment by lucasvanhalst** [comment]
I'm guessing you could use https://pypi.python.org/pypi/autopep8 for this

**Comment by iwanbk** [comment]
> I'm guessing you could use https://pypi.python.org/pypi/autopep8 for this

Thx for the suggestion!

**Comment by iwanbk** [comment]
I just tried to run autopep8 without option against the generated `client.py`, it only fixed these:
- trailing whitespace
- blank line contains whitespace

It didn't fix `line too long`

Add the `--max-line-length=79` to the command option didn't help.

It seems to be limitation of `autopep8` https://github.com/hhatto/autopep8/issues/39.

In this case, it seems we still need to work on the template

**Comment by zaibon** [comment]
You need to run it with `- - aggressive` if you want it to fixe something else then with spaces.
Regarding line length, I don't think we should force 80 characters. I find it way to short. We're not in the 80's anymore

**Comment by iwanbk** [comment]
It seems that we don't need to use `autopep8` for these reasons:
- most of blank line and white space issue can be and already fixed in the template (in python-client-pep8 branch)
- autopep8 can't solve things that not so easy to be fixed in the template, like `line too long` issue.

**Comment by zaibon** [comment]
@iwanbk check my previous comment. 
autopep8 CAN deal other problem then blank line.

**Comment by iwanbk** [comment]
> @iwanbk check my previous comment.
> autopep8 CAN deal other problem then blank line.

Oh, you're right.

**Comment by iwanbk** [comment]
Missed other issues because based on `pycodestyle` our generated code only has space and long lines,
but there is big chance that i missed other issues or we have new issues in the future

**Comment by iwanbk** [comment]
so, i propose to run `autopep8` with this options
```
autopep8 -a -a --in-place file.py
```

any other suggestion @zaibon @lucasvanhalst ?

**Comment by zaibon** [comment]
This will break line longer then 80 chars. Is it what we want ?
I'm not a big fan of the 80 chars limit.

Other then that, yeah seems reasonable.

**Comment by iwanbk** [comment]
> This will break line longer then 80 chars

Not always, but yeah it tries to do it.

> Is it what we want ?
> I'm not a big fan of the 80 chars limit.

Why not, it is the default value of pep8 docs and `pycodestyle` tool

**Comment by zaibon** [comment]
no reason, just I find this a bit ridiculous that in 2017 to limit a line at 80 characters. But that's just personal preference.

**Comment by lucasvanhalst** [comment]
I'd make the max line length at least 120 characters, because 80 is a bit cramped as zaibon said

**Comment by iwanbk** [comment]
> I'd make the max line length at least 120 characters

@zaibon agree with this value? your call

**Comment by zaibon** [comment]
LGTM

**Comment by iwanbk** [comment]
Implemented at #385
