### ISSUE TITLE
oauth2 support

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#36]
@robvanmieghem @zaibon 
I am designing oauth 2 support now, i think we should implement it to follow the flow described in https://aaronparecki.com/2012/07/29/2/oauth2-simplified#web-server-apps.
If we choose Facebook as example, the flow would be:

1. REST API server provide HTML login page with 'sign in with facebook' button.

2. When user click the button, user will be redirected to facebook login page (`authorizationUri`)

3. In succesfull login, user will be redirected back to REST server with access_code.

4. With that access code, REST server can ask for access_token using URI specified in `accessTokenUri`

5. REST server save access_token

6. REST server give access_token as response to user.

Most of the points are pretty clear, except point (5). I think redis is pretty common for this use case. But considering we also want to use mongodb in v0.3, it is worth to consider to use mongodb to save access_token data.

**Comment by robvanmieghem** [comment]
From an api perspective, most important thing is to support the raml notation of declaring oauth security.
I would not bother too much with the how the user or application got the oauth token, as long as it has one it is fine. Generating some middleware that is applied on the routes where the actual scope check is left open seems fine as a first step.

**Comment by iwanbk** [comment]
initial implementation on #39

**Comment by iwanbk** [comment]
Go support implemented on #39, #40, #41, #44, #45.

Python support implemented on #46
