### ISSUE TITLE
[python] URL encode url parameters

### ISSUE THREAD

**Issue by lucasvanhalst** [Jumpscale/go-raml#373]
Instead of just concatenating the url, it should url encode the parameters

See  here for example https://github.com/itsyouonline/identityserver/blob/1.0.0/clients/python/itsyouonline/organizations_service.py#L9-L15

**Comment by iwanbk** [comment]
thx @lucasvanhalst 
Any PR is welcomed.
Even the example of how the generated files should look like will be appreciated.

**Comment by lucasvanhalst** [comment]
Example:

```python
from six.moves.urllib.parse import quote

class OrganizationsService(object):
    def __init__(self, client):
        self.client = client

    def Get2faValidityTime(self, globalid, headers=None, query_params=None, content_type="application/json"):
        """
        Get the 2FA validity time for the organization, in seconds
        It is method for GET /organizations/{globalid}/2fa/validity
        """
        uri = self.client.base_url + "/organizations/"+quote(globalid)+"/2fa/validity"
        return self.client.get(uri, None, headers, query_params, content_type)
```

**Comment by iwanbk** [comment]
thx @lucasvanhalst 

How about place the `quote` inside `self.client.get` function?
This way we could avoid a lot of code duplication.

**Comment by lucasvanhalst** [comment]
Guess that would work as well. But also put it in post / put / delete then

**Comment by iwanbk** [comment]
@lucasvanhalst 
After some experiment, i think it already handled by python-requests library we use.

I tried by sending variable that contains space.
Both flask & goji server could accept it fine.
Flask also printed the URL, the space already encoded to `%20`

**Comment by bart-at-mobicage** [comment]
Hi @iwanbk, the space is not the issue. It are characters like é, ü or Russian characters that cause problems.

As update to @lucasvanhalst his comment... in python2 the `quote` method doesn't accept unicodes, so the need to be encoded to strings.

```python
    def RemovePendingOrganizationInvitation(self, username, globalid, headers=None, query_params=None, content_type="application/json"):
        """
        Cancel a pending invitation.
        It is method for DELETE /organizations/{globalid}/invitations/{username}
        """
        username_str = username.encode('utf-8') if isinstance(username, unicode) else username
        globalid_str = globalid.encode('utf-8') if isinstance(globalid, unicode) else globalid
        uri = self.client.base_url + "/organizations/"+quote(globalid_str)+"/invitations/"+quote(username_str)
        return self.client.delete(uri, None, headers, query_params, content_type)
```

**Comment by iwanbk** [comment]
Not really blocked by #400, but will wait for #400 to be merged to avoid re-updating the test fixture.
