### ISSUE TITLE
python client: incorrect generation when the root url has parameters

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#392]
If you try to generate a python client for the following raml, the generated client will have broken files for this resource. The problem exists for any endpoint for which the root is not a single object (multiple slashes)
```
/orgs/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: Org
```
however, if you change it to the following, it will generate just fine,
```
/orgs:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Org
```

**Comment by iwanbk** [comment]
I found that:
- the issue is the generator simply forget to call `commons.NormalizeURI`
- golang client also has same issue

The code for the fix already done, i'm adding the tests now
