### ISSUE TITLE
Refactor client code organization

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#394]
I have a proposition to simplify the python client  code that is generated.
This will provide a nicer interface for the user and hide all the business logic from the user. So he would only see the actual methods he cares about.

Required changes:
- remove client.py, this is not needed
- update `__init__.py` to expose only the methods the user cares about
- create an `httpclient.py` module that abstract all http logic out and hide it from the user

Check the content of the zip file for a full example :
[client.zip](https://github.com/Jumpscale/go-raml/files/1590986/client.zip)

**Comment by serboctor** [comment]
The __init__.py also contains the security schemes and I guess that's why we had both files, if we remove client.py and move all the api resources to __init__.py they'll be on the same level with the security like so:
```
from .node_service import NodeService
from .orgs_service import OrgsService

from .oauth2_client_itsyouonline import Oauth2ClientItsyouonline
from .oauth2_client_anotherauth import Oauth2ClientAnotherauth
from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri="", token=None):
        http_client = HTTPClient(base_uri, token)

        self.oauth2_client_itsyouonline = Oauth2ClientItsyouonline()
        self.oauth2_client_anotherauth = Oauth2ClientAnotherauth()
        self.node = NodeService(http_client)
        self.orgs = OrgsService(http_client)
```
would this be ok? an alternative solution is to create a security class and reference it:
```
class Client:
    def __init__(self, base_uri="", token=None):
        http_client = HTTPClient(base_uri, token)

        self.api_security = Security()
        self.node = NodeService(http_client)
        self.orgs = OrgsService(http_client)


class Security:
    def __init__(self):
        self.oauth2_client_itsyouonline = Oauth2ClientItsyouonline()
        self.oauth2_client_anotherauth = Oauth2ClientAnotherauth()
```

**Comment by zaibon** [comment]
In normal use case I guess we won't have too many different security scheme. 
But in the case we do, having it at the same level is going to be messy, so I would go for version 2, with a `security` attribute that bundle all security scheme together

**Comment by serboctor** [comment]
I think `security` is too generic and might easily exist in the resources and conflict with it. So I suggest `api_security` or `security_schemes`

**Comment by zaibon** [comment]
I vote for `security_schemes`
