### ISSUE TITLE
Python client: Add support for type: array in response body

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#396]
from the raml:
```raml
responses:
  200:
    description: Success
    body:
      application/json:
        displayName: response
        type: array
        items:
          type: Label
```
Go-raml doesn't support this type of array notation. The code generated from this raml looks like this:
```python
if resp.status_code == 200:
    resps = []
    for elem in resp.json():
        resps.append(elem)
    return APIResponse(data=resps, response=resp)
```

While it should be :
```python
if resp.status_code == 200:
    resps = []
    for elem in resp.json():
        resps.append(Label(elem))
    return APIResponse(data=resps, response=resp)
```

Make sure to support this notation in all possible occurrence. In Types, request body, response body.

Also, for any resources that include this type of notation, the generated <resource>_service.py will contain an incorrect import `from . import` which completely breaks the file and makes the whole client unusable. 
This is due to the fact that the `items` property is not properly handled from the beginning when we create the types and at this point in the code it is empty hence the import which would have otherwise been `from .Label import Label`.

**Comment by iwanbk** [comment]
> This is due to the fact that the items property is not properly handled from the beginning when we create the types

Yep, it is handled if declared in `types` but not the case with inline type in response body.

**Comment by iwanbk** [comment]
The `items` field is indeed not exist in the parser, need to add and handle it properly.
