### ISSUE TITLE
Golang server: change generated file layout for easier re-generation 

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#405]
Blocked by #393 and should take inspiration from that issue

**Comment by iwanbk** [comment]
By looking at #393, basically `--api-file-per-method` already do the right things.
Improvements we can do:
- make the `--api-file-per-method` as default behavior. 
- add notices on top of the file, add info whether the file will be regenerated or not
- add docs

any comment @serboctor @zaibon ?

**Comment by serboctor** [comment]
Yep, --api-file-per-method already handles it. You just need to change the override flag in all the `commons.GenerateFile` calls to make sure that everything is overwritten except for the api files. And please do the same for the client too, I did that for the python client too.
Is it possible for the server to may be create some directories to make things a bit more structures instead of generating everything on the root path? or will this mess up the go imports? I think may be it can be similar to python, where types are in a `types` dir and the method files are in another dir and on the root we just have the main and the interfaces? The current generation becomes overwhelming if you're generating for a large raml file with lots of apis.

**Comment by iwanbk** [comment]
> Yep, --api-file-per-method already handles it.
cool

> You just need to change the override flag in all the commons.GenerateFile calls to make sure that everything is overwritten except for the api files. And please do the same for the client too, I did that for the python client too.

ok

> Is it possible for the server to may be create some directories to make things a bit more structures instead of generating everything on the root path? or will this mess up the go imports? 

Of course it is possible and also need us to update the import path

**Comment by iwanbk** [comment]
>  where types are in a types dir

Because it is in separate dir, the type need to be exported  for it to be used by other packages.
It has some implication.
- type name need to be changed to be started by upper case letter -> shouldn't be a big problem to modify the generator
- first letter of the type name will be case insensitive. I think no sane developers will have (for example) `User` and `user` in their RAML types,  but who knows, it is valid raml anyway

> the method files are in another dir 

need the types to be in separate dir

**Comment by serboctor** [comment]
> first letter of the type name will be case insensitive. I think no sane developers will have (for example) both User and user in their RAML types, but who knows, it is valid raml anyway

I am personally ok with that. I think the current structure is overwhelming. And as long as we document these assumptions, then it shoud be fine. But I'd rather have @zaibon's input too.

**Comment by iwanbk** [comment]
> first letter of the type name will be case insensitive. I think no sane developers will have (for example) both User and user in their RAML types, but who knows, it is valid raml anyway

I curiously checked how go-swagger handle this case. I have two types : `Item` and `item`.
go-swagger only generates one type : `Item`, which could be `item` or `Item`.
I think this is not the right way to do.

My proposal: the parser checks whether we have conflicted types like above, if it happens, go-raml exits

**Comment by iwanbk** [comment]
@serboctor @zaibon if there is no objection, i'll implement it

**Comment by zaibon** [comment]
> My proposal: the parser checks whether we have conflicted types like above, if it happens, go-raml exits

This sounds like a sane things to do.

**Comment by serboctor** [comment]
Sounds good to me
