### ISSUE TITLE
Tarantool/Lua server : change generated file layout for easier re-generation 

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#406]
Blocked by #393 and should take inspiration from that issue

**Comment by iwanbk** [comment]
From what i can see, Tarantool/Lua server layout already similar to new python layout. Improvements we can make:
- add notices on top of each file, whether the file will be regenerated or not. We only regenerate the handlers
- add docs

**Comment by iwanbk** [comment]
@serboctor @zaibon please add your concern here

**Comment by serboctor** [comment]
It is actually not the same as python, the handlers are directly references in the routes and all handlers group belonging to the same endpoint are in the same file so all of this will need to be changed.

**Comment by serboctor** [comment]
@zaibon @iwanbk any objects on the attached structure? 
[test.tar.gz](https://github.com/Jumpscale/go-raml/files/1629543/test.tar.gz)

**Comment by iwanbk** [comment]
> @zaibon @iwanbk any objects on the attached structure?

i'm OK with it.

We also need Lua generator tutorial
