### ISSUE TITLE
Python : add support for type alias

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#409]
- [x] python class (#412)
- [ ] jsonschema
- [ ] python capnp

It was previously discussed at https://github.com/Jumpscale/go-raml/issues/228#issuecomment-353972595

To add proper support for type alias, we need to touch these three submodules:

(1) python class generator

For non builtin type, we can simply creates the class as alias of the aliased type
```python
NewClass = AliasedType
```
This is the mapping for aliased type
```go
typeMap := map[string]string{
        "string":   "str",
        "integer":  "int",
        "int":      "int",
        "int8":     "int",
        "int16":    "int",
        "int32":    "int",
        "int64":    "int",
        "long":     "int",
        "number":   "float",
        "double":   "float",
        "float":    "float",
        "boolean":  "bool",
        "datetime": "datetime",
        "object":   "dict",
        "UUID":     "UUID",
    }
```

(2) json schema:

After some digging, i think we need to consider to use external tool to generate the json schema.
I found a promising tool https://github.com/raml-org/ramldt2jsonschema and tracked the work at #408 

(3) python capnp

No idea about it for now, @serboctor ?

**Comment by iwanbk** [comment]
python class part has been implemented at #412 (waiting for review/merge).

Now checking the json schema

**Comment by iwanbk** [comment]
> After some digging, i think we need to consider to use external tool to generate the json schema.
I found a promising tool https://github.com/raml-org/ramldt2jsonschema and tracked the work at #408

It is not interesing anymore because it needs the type name to be generated, which might indicate that it doesn't support inline type. 

I also think that the json schema alias looked quite simple:
- alias of builtin type :  we simply can't support it, builtin type can't be a JSON, except the `object` type
- alias of non builtin type : it seems we can use `ref`

**Comment by iwanbk** [comment]
> alias of non builtin type : it seems we can use ref

Current generator do this by copying all the fields from the aliased type. It serve our purpose (as input validation), but might not the correct way to use json schema.
Still need to check whether we can use `ref`

**Comment by iwanbk** [comment]
> Still need to check whether we can use ref

we can use `$ref` for json type alias, the code has been finished.

There is still work left. We need to disable json schema checking when the request body is builtin type, not raml type.

**Comment by serboctor** [comment]
I don't really see anything in the capnp docs that can help us alias a struct as a built-in type, this concept doesn't really exist in capnp. @zaibon do you have a different input?
