### ISSUE TITLE
Including a securityscheme fails if it is included on the same line

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/go-raml#42]
According to the spec, including a securityscheme should be possible like this:
```
securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth_2_0.raml
```

The parser fails with:
```
ERRO[2016-03-21T10:58:14+01:00] Error parsing RAML:
  yaml: line 4: mapping values are not allowed in this context
```

If the securityscheme is included on a new line:
```
securitySchemes:
  - oauth_2_0:
        !include securitySchemes/oauth_2_0.raml
```
This does work because the final yaml (after the inclusion is valid now). I think a newline should be added before the included text.

**Comment by iwanbk** [comment]
fixed in #45
