### ISSUE TITLE
User relative import for python server

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#420]
In the app.py and the xx_api.py files we should use relative imports.

For example in app.py:
change
```python
from blueprints_api import blueprints_api to
```
to
```python
 from .blueprints_api import blueprints_api
```
For this to work, the server directory should be a package, so also add an __init__.py file in the server folder.

and in the xx_api.py files:
change 
```python
import handers
```
to
```python
from . import handlers
```

**Comment by serboctor** [comment]
Reverted this change in https://github.com/Jumpscale/go-raml/pull/437/ because it breaks the server if it is not being imported in another module.
We need to think of a better way to do this, relative imports break the server when we directly run `python3 app.y` and non-relative imports makes the app unusable if we want to import it in another module.

**Comment by iwanbk** [comment]
We can do something like this

```python
try:
    from .escape_type_api import escape_type_api
except SystemError:
    from escape_type_api import escape_type_api
```
It works when i call `app.py` from same directory.
But i don't know the risk of doing this.

**Comment by iwanbk** [comment]
@zaibon @serboctor any comment about my proposed solution at https://github.com/Jumpscale/go-raml/issues/420#issuecomment-359657003

**Comment by zaibon** [comment]
I'm OK with it

**Comment by zaibon** [comment]
actually the more I think about this the more I wonder if we should not do it differently.
Currently the generated code for the server just expect we start the server from the app.py

while in real life you probably don't want to do that.
I never had a project where I can just use the app.py as main file.

What I usually do is having a main file out of the server directory from whre I import the app module.
So basicly the server generated code is a library, and the I use it to build my main file.

If we structure it like this. we can always use relative import cause we'll never use app.py as main file.
but then I guess we need to somehow install the server lib before being able to use it

so maybe we could also generate a setup.py that install stuff properly so it's all ready to be used ?

**Comment by iwanbk** [comment]
> while in real life you probably don't want to do that.
> I never had a project where I can just use the app.py as main file.

I had few experiences with flask, all of them use `app.py` directly.
It might only show how inexperienced i am with flask/python.

> you can check how I did that for 0-robot: https://github.com/Jumpscale/0-robot/blob/master/cmd/zrobot

thanks. will check

**Comment by zaibon** [comment]
In simple server example they usually use app indeed. but since here the app.py is re-generated everytime, you can change anything in there.
So if you need some special initalization for database or CLI argument for example, you need to import the app in another module anyhow

**Comment by iwanbk** [comment]
> actually the more I think about this the more I wonder if we should not do it differently.

To make sure i understood you correctly, you proposed to make it only import relatively, right?

> So if you need some special initalization for database or CLI argument for example, you need to import the app in another module anyhow

Yeah, i think almost all application, even the simple one, need to do this.

**Comment by zaibon** [comment]
> To make sure i understood you correctly, you proposed to make it only import relatively, right?

Yes, if we somehow also generate a main file that is outside of the generated server package.
So the app.py will always be imported and not used directly.

But maybe this is a bit too much and will make the accessilibty of thet generated server less easy for beginners. I'm really puzzled about all this.

Now the try/except ImportError is a really simple solution and that doesn't require change anywhere else in the code. These are the pro and cons I guess.

**Comment by iwanbk** [comment]
> But maybe this is a bit too much and will make the accessilibty of thet generated server less easy for beginners. I'm really puzzled about all this.

This is true

> Now the try/except ImportError is a really simple solution and that doesn't require change anywhere else in the code

Yeah.

Given those reasons, i propose (again) the try/except import solution

**Comment by iwanbk** [comment]
will work on this try-except-importError solution as this is needed for #455.
Without this we can't import the generated server from other directory.

**Comment by zaibon** [comment]
They other day I was looking at the flag proposed by go-raml for server generation and I noticed the `--no-main` flag. This made me think about this issue. The problem we're trying to solve here is in the case we import the generated server into another project and use it as a librairy. This description fits perfectly with the `--no-main` flag.

So I think the right way to solve this issue is, when we generate without `--no-main` we use absolute import. Cause we generated the server with the ide that it's full server with a main.

If we generate with `--no-main` then we don't create an `app.py` file and we use relative import cause the generated code is meant to be imported by another project, and thus relative import is safe. 
So in this case the only thing we need to chane is in the `xx_api.py` files, use `from . import handlers` instead of `import handlers`

**Comment by iwanbk** [comment]
> So I think the right way to solve this issue is, when we generate without --no-main we use absolute import. Cause we generated the server with the ide that it's full server with a main.
> 
> If we generate with --no-main then we don't create an app.py file and we use relative import

It seems to be a clean solution
