### ISSUE TITLE
DELETE methods are turned into GET methods in the golang generated client

### ISSUE THREAD

**Issue by LeeSmet** [Jumpscale/go-raml#421]
When generating a golang client from a raml, all DELETE methods will perform a GET request. For example, the following raml fragment:

```RAML
delete:
          displayName: DeleteOrganizationAPIKey
          description: Removes an API key
          responses:
            204:
              description: API key removed
```
[original raml](https://github.com/itsyouonline/identityserver/blob/3121c59e1ad255fb4142855d91c70e26d37d2761/specifications/api/itsyouonline.raml#L2111-L2116)

generates the following code:

```Go
// Removes an API key
func (s *OrganizationsService) DeleteOrganizationAPIKey(label, globalid string, headers, queryParams map[string]interface{}) (*http.Response, error) {
	var err error

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/organizations/"+globalid+"/apikeys/"+label, headers, queryParams)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	return resp, err
}
```
[actual code file](https://github.com/itsyouonline/identityserver/blob/3121c59e1ad255fb4142855d91c70e26d37d2761/clients/go/itsyouonline/organizations_service.go#L46-L57)

It seems to me the problem is located here (Notice the hardcoded `"GET"` on line 26):
https://github.com/Jumpscale/go-raml/blob/572fc7c6bb66cdb2e8adf7e8fd375c071ea12424/codegen/templates/golang/client_service_go.tmpl#L25-L29

**Comment by iwanbk** [comment]
super bad mistake, fixed at #422
