### ISSUE TITLE
unmarshal does not work?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#426]
instructions not ok in
https://github.com/Jumpscale/go-raml/blob/master/docs/python_generator.md

**Comment by despiegk** [comment]
--python-unmarshall-response=true

**Comment by serboctor** [comment]
> unmarshal does not work?

It does work, as per the document this is for the client generation not the server.

> instructions not ok in
https://github.com/Jumpscale/go-raml/blob/master/docs/python_generator.md

 What would like to have changed in the docs? it already has the relevant command and an example of the generation.

**Comment by serboctor** [comment]
Moved the `unmarshall response` docs to https://github.com/Jumpscale/go-raml/blob/master/docs/tutorial/python/README.md to be with all the other details about all possible python commands and options.
