### ISSUE TITLE
js9 not used

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#429]
the idea & goal was that people could use easy tool from js93, not usable today

.../code/github/jumpscale/lib9/JumpScale9Lib/tools/raml/RamlTools.py

**Comment by despiegk** [comment]
in branch development

**Comment by serboctor** [comment]
> the idea & goal was that people could use easy tool from js93, not usable today

What is not usable about it? Did you run `js9_raml upgrade` to make sure you have the latest go-raml code. It is impossible to fix a problem if we don't know what is the problem. What did you try to generate? which commands did you use?
