### ISSUE TITLE
could not get generation to work for python

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#431]
- losing hours with it, doc not complete, command lines changed
- the types are not checked
- return codes not done well in go-raml

please fix asap & test

**Comment by serboctor** [comment]
> losing hours with it, doc not complete, command lines changed

which docs are not complete? there are several docs. The readme at the home page contains the basic commands. The following contains more extensive info 
https://github.com/Jumpscale/go-raml/tree/master/docs/tutorial/python
https://github.com/Jumpscale/go-raml/blob/master/docs/python_generator.md

>the types are not checked 

what do you mean by that? which types aren't checked?is this in the client or the server?

>return codes not done well in go-raml

In what sense? in the server we validate the payload and raise a bad request, anything else will need to be done by the user anyway.
