### ISSUE TITLE
generated client does not seem to work?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#432]
![image](https://user-images.githubusercontent.com/6021844/35184575-e6a59586-fdf7-11e7-956c-159613c7e2ee.png)

also different styles of methods?

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/35184873-59f87be0-fdfb-11e7-85fa-87afb37295e4.png)

**Comment by despiegk** [comment]
make sure following works:

js9 'j.tools.raml.test()'

on development branch of js9 for lib/core

**Comment by serboctor** [comment]
>make sure following works:
js9 'j.tools.raml.test()'
on development branch of js9 for lib/core

I tested it on development after updating my repos, running js9_upgrade, then running the tests. And everything works fine and the tests pass.

>also different styles of methods?

This depends on the raml....if a `displayName` is defined for the resource, then this name is used as the api function name.

> not enough methods on client eg: no list

This also depends on the raml, if it is not defined in the raml, it won't be in the client. And there isn't much I can do without seeing the raml used to generate this.

**Comment by serboctor** [comment]
I checked the userList issue, this is due to a bad raml in the baseapp of js9_raml. I fixed it in this commit https://github.com/Jumpscale/lib9/commit/6eec2215544e16137cc1b73242d3690fa4852d64
