### ISSUE TITLE
Include commit hash and real version in binary

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#433]
![image](https://user-images.githubusercontent.com/6021844/35184643-ca010978-fdf8-11e7-839b-534ef7e7d747.png)

something need to be bumped, so we know doc in line with tool

**Comment by zaibon** [comment]
Use something like done in 0-stor to include commit hash, build date and the real version number:
example: 
https://github.com/zero-os/0-stor/blob/master/Makefile#L18
https://github.com/zero-os/0-stor/blob/45e5ea4ad3e079480249044fec51af5a66c6a474/cmd/version.go#L30-L47

**Comment by iwanbk** [comment]
```
real version number
```

Do we need to follow other jumpscale projects for versioning?

**Comment by zaibon** [comment]
To me just using jumpscale version doesn't make any sense but seems all repo in jumpcale account have same version, so I don't know.
@despiegk any comment ?

**Comment by rkhamis** [comment]
I don't think they should have the same version, but milestone-wise, it's easier to keep track

I'd prefer to have v1.0.0 here, let me know if I should change milestone names
