### ISSUE TITLE
oauth test

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#435]
Test allowing certain scopes in oauth2

**Comment by iwanbk** [comment]
Previously discussed at https://github.com/Jumpscale/go-raml/pull/423#discussion_r162527177

**Comment by iwanbk** [comment]
The `scopes` fixture in  https://github.com/Jumpscale/go-raml/blob/b9eca4d40342af7e1dd769d107c42bee1fbf9499/codegen/python/fixtures/security/oauth2_Facebook_ADMINISTRATOR.py is indeed obsolete.

The allowed scopes are passed as argument to middleware constructor https://github.com/Jumpscale/go-raml/blob/643ff8158aa7bd0cdfeffad3710980f307206476/codegen/python/fixtures/security/deliveries_api.py#L13-L14
