### ISSUE TITLE
Add support for recursive ressource path

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#442]
- [x] Go (#444)
- [x] Python (#445)
- [ ] Tarantool

In one of our project we want to describe a file system like API. Which means we need to be able to catch the full path of a ressource and use it as argument to the handlers.

Something like:
```raml
/myressource/{path:path}:
   get:
       ....
```
url: `/myressource/foor/bar/test` needs to give `/foo/bar/test` as argument to the handler
url: `/myressource/` needs to give `/` as argument to the handler
url: `/myressource` needs to return 404 cause we don't handle this path.

The notation {path:path} comes from flask, this is how they express catch all path. We could think of something else like {path:*} or something.

more info for flask: http://flask.pocoo.org/snippets/57/
I know gorilla mux also support this, needs to check what's the correct notation

#### update (iwan):
- we use ` {path:*}` notation

**Comment by iwanbk** [comment]
@zaibon 
don't you think we can easily send the filepath by escaping/quoting it from the client?

**Comment by iwanbk** [comment]
> don't you think we can easily send the filepath by escaping/quoting it from the client?

geert said that we can, but it is not nice.
I'm checking gorilla mux now.

**Comment by iwanbk** [comment]
I have tried both Go and python server
Go 
```go
/users/{path:.*}
```

Python
```python
@app.route('/users/', defaults={'path': ''})
@app.route('/users/<path:path>')
```
> url: /myressource/foor/bar/test needs to give /foo/bar/test as argument to the handler
> url: /myressource/ needs to give / as argument to the handler

both Go and python give the path without leading `/`:
- `/foo/bar/test` `foo/bar/test`
- `/` -> ``

Is it OK @zaibon ?

> url: /myressource needs to return 404 cause we don't handle this path.

Go work as expected, Python gave 301, need to check.

**Comment by zaibon** [comment]
> both Go and python give the path without leading /:
/foo/bar/test foo/bar/test
/ -> ``

Hum I guess there is no way around it. And This needs to be handled in the handlers.
if path is `/`, it's the root, if path doesn't start with `/` then it's a path to something and we need to considider it starts with `/`

**Comment by iwanbk** [comment]
>> url: /myressource needs to return 404 cause we don't handle this path.

> Go work as expected, Python gave 301, need to check.

From https://stackoverflow.com/a/21050582/6935088, we could fix it by add  `strict_slashes=False` to the route.
But it gave `200` instead of `404`.

Any idea @zaibon @serboctor ?

complete flask file

```python
from flask import Flask, jsonify
app = Flask(__name__)

@app.route('/users/', defaults={'path': ''}, strict_slashes=False)
@app.route('/users/<path:path>')
def catch_all(path):
    return jsonify(name=path)

if __name__ == '__main__':
    app.run(debug=True)
```

could be easily tested with `curl`
```bash
curl -i http://127.0.0.1:5000/users
```

**Comment by zaibon** [comment]
> But it gave 200 instead of 404.

This is fine let's go for that.

**Comment by zaibon** [comment]
I just tested the new feature for go server generation.
I used this raml spec: https://gist.github.com/zaibon/9b30996ec1018c5f7c857ed7a78331ed#file-meta-raml

The generated type for the routing interface is :
```go
type Path:.*Interface interface{
```

The name of the file is also 
```
path:.*`_if`.go
```

@iwanbk ;-)

**Comment by iwanbk** [comment]
my bad, i didn't test it when become root endpoint,  #446 should fix it

https://gist.github.com/zaibon/9b30996ec1018c5f7c857ed7a78331ed#file-meta-raml-L80-L81
this is wrong syntax btw
```yaml
/{path:.*}`:
```
should be
```
/{path:*}
```

this line https://gist.github.com/zaibon/9b30996ec1018c5f7c857ed7a78331ed#file-meta-raml-L137 also need to be fixed

**Comment by iwanbk** [comment]
@serboctor could you check the tarantool?

**Comment by iwanbk** [comment]
Tarantool moved to own issue
