### ISSUE TITLE
Generated comments are not golint compliant

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/go-raml#49]
Currently the following raml
```
/users/address:
      /{addressId}:
        get:
          displayName: GetUserAddressByID
          description : gets the address by id
```

generates the following go code:
```
	// gets the address by id
	// It is handler for GET /users/{userId}/address/{addressId}
	GetUserAddressByID(http.ResponseWriter, *http.Request)
```

It would be better and more readable if it would be this:
```
	// GetUserAddressByID is the handler for GET /users/{userId}/address/{addressId}
	// gets the address by id
	GetUserAddressByID(http.ResponseWriter, *http.Request)
```

This will prevent `golint` from issueing a warning since this comment is according to go best practices.

**Comment by iwanbk** [comment]
nice catch @robvanmieghem. 

I think we also need add comment to:
-  API struct https://github.com/Jumpscale/go-raml/blob/21316a730b08f6007bc60b301dc0eb30994cd01e/commands/fixtures/server_resources/deliveries_api.txt#L6

- Interface struct https://github.com/Jumpscale/go-raml/blob/21316a730b08f6007bc60b301dc0eb30994cd01e/commands/fixtures/server_resources/deliveries_if.txt#L10

**Comment by robvanmieghem** [comment]
@iwanbk You are right
