### ISSUE TITLE
too difficult to get started

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#68]
building did not work
not clear how to install deps

this build.sh gives errors

**Comment by iwanbk** [comment]
Sorry for this inconvenience, just realised that build instruction is outdated, but build.sh script still work.

I think you have fixed build instruction, i tried it in clean installation and it worked.

**Comment by despiegk** [comment]
![image](https://cloud.githubusercontent.com/assets/6021844/14342207/15e09d5c-fca9-11e5-842a-55d19e42d0ca.png)

cannot use the example which I've put there

**Comment by despiegk** [comment]
see python example, is on my mac though

**Comment by iwanbk** [comment]
I also use Mac.

Please use latest Go version, Go 1.6

**Comment by despiegk** [comment]
ok now it works

**Comment by despiegk** [comment]
![image](https://cloud.githubusercontent.com/assets/6021844/14342934/ac9708da-fcae-11e5-80d5-713c8964d48b.png)

next issue
no doc whatsover

why can't we go by default to /explorer/ and show a UI for the rest calls

at least create some examples 
or explain how to use

**Comment by despiegk** [comment]
at least create some examples, one in golang one in python
make sure docs are exposed from webserver
put a nicer raml file in there
