### ISSUE TITLE
Raml-1.0-rc2 support

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#80]
We need to make sure that our implementation is compatible with raml-10-rc2

**Comment by sichvoge** [comment]
Any ETA for the support of RC2. The spec closed RC2 as a GA-based release. It would be great to see the go-raml + parser to fully support RAML 1.0.

**Comment by iwanbk** [comment]
@sichvoge it should be next wednesday - next friday.

**Comment by sichvoge** [comment]
Awesome! Thanks.

**Comment by iwanbk** [comment]
@sichvoge raml1.0-rc2 has been merged to master

**Comment by sichvoge** [comment]
@iwanbk is the [limitation](https://github.com/Jumpscale/go-raml/blob/master/docs/limitations.md) file updated?

**Comment by iwanbk** [comment]
@sichvoge
We have some library support, still not finished, tracked in #89
