### ISSUE TITLE
yaml parser test failed in Go 1.6

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/go-raml#92]
PR has been sent to mainstream repo 
https://github.com/buddhamagnet/yaml/pull/1.
Waiting to be accepted.

**Comment by iwanbk** [comment]
looking at my PR which already 1.5 months without any response, i think it is better to fork the repo.

@zaibon @robvanmieghem 
doest gigforks still the good place to fork it?

@robvanmieghem 
If we have the time, i think it is better to fork the original repo (https://github.com/go-yaml/yaml).
And then bring regexp support from buddhamagnet to our go-yaml/yaml  fork.

**Comment by robvanmieghem** [comment]
@iwanbk I thing you are right

**Comment by robvanmieghem** [comment]
@iwanbk discusses with Kristof, you can use gigforks for now
